pipeline {
    agent any

    environment {
        DOCKERHUB_CREDS=credentials('lab_1')
        LC_ALL = "en_US.UTF-8"
        LANG    = "en_US.UTF-8"
        LANGUAGE = "en_US.UTF-8"
    }

options {
        timestamps()
        skipDefaultCheckout(true)
	}
    stages {
        stage('Clone github repository') {
            steps {
                cleanWs()
                bat 'chcp 65001 && git clone -b main https://github.com/msidorov11/lab_1.git'
				}
			}

        stage('Checkout repo dir') {
            steps {
                bat 'chcp 65001 && cd lab_1 && dir'
				}
			}

        stage('Login'){
            steps{
                bat 'chcp 65001 && docker login -u %DOCKERHUB_CREDS_USR% -p %DOCKERHUB_CREDS_PSW%'
                }
            }

        stage('Create and run docker container') {
            steps {
                script {
                    try {
                        bat 'chcp 65001 && cd lab_1 && docker-compose build'
                        }

                    finally {
                    bat '''
                        chcp 65001
                        cd lab_1
                        docker-compose up -d
                        '''
                        }
				    }
                }
            }

        stage('Checkout container logs') {
            steps {
                dir("lab_1") {
                        bat '''
                            docker-compose up -d
                            for /f %%i in ('docker ps -qf "name=^lab_1-web-1"') do set containerId=%%i
                            echo %containerId%
                            IF "%containerId%" == "" (
                                echo "No container running"
                            )
                            ELSE (
                                docker logs --tail 1000 -f %containerId%
                                )
                        '''
                    }
            }
        }

        stage('Checkout coverage report'){
            steps{
                dir("lab_1"){
                    bat '''
                    docker-compose logs -t --tail 10
                    '''
                }
            }
        }

        stage('Push'){
            steps{
                bat 'chcp 65001 && docker push msidorov11/lab_1:latest'
            }
        }
	}

    post {
        always {
            bat 'chcp 65001 && docker logout'
        }
    }
}